name: AndyOlympics
favicon: null
layout_spectrum: 0.15998874395154417
typography_spectrum: 0.3845738514792174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5739377569407225
  lightness: 0.869429531507194
  saturation: 0.32936122897081077
  rhythmicContrast: 0.3597207781858742
purpose: []
